server {
    listen 80;

    # Web Statis → root /
    location / {
        proxy_pass http://web-static:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Web Dinamis → /perpustakaan/
    location /perpustakaan/ {
        proxy_pass http://web-dinamis:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }
}

server {
    listen 3000;

    # Web Dinamis on port 3000
    location / {
        proxy_pass http://web-dinamis:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }
}
