name: CI/CD Pipeline - UAS MultiApp

on:
  push:
    branches: [main]

jobs:
  build-static:
    name: Build Web Statis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./web-static
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-static-uas:latest

  build-dinamis:
    name: Build Web Dinamis PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-dinamis-uas:latest

  deploy:
    name: Deploy ke AWS EC2
    runs-on: ubuntu-latest
    needs: [build-static, build-dinamis]
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,nginx/,docker/"
          target: "~/uas-app"
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/uas-app
            docker pull ${{ secrets.DOCKER_USERNAME }}/web-static-uas:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/web-dinamis-uas:latest
            docker stop web-static || true
            docker rm web-static || true
            docker run -d --name web-static --network uas-app_appnet kakangwildan/web-static-uas:latest
            docker compose up -d --no-deps --force-recreate web-dinamis nginx
            docker image prune -f
            echo "Deploy selesai $(date)"
